import NavBar from "@/componentes/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/componentes/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Api Crud Next 🍺 JUAMAYA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <div className="h-screen">
          <NavBar/>
          <div className="mt-8 mx-auto p-4">
            {children}
          </div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
